import { MaterialCommunityIcons } from "@expo/vector-icons";

export type PlantLevel = "Beginner" | "Moderate" | "Advanced" | "Sage";

export interface Plant {
  key: string;
  name: string;
  scientificName: string;
  desc: string;
  badge: string;
  badgeIcon: keyof typeof MaterialCommunityIcons.glyphMap;
  badgeIconColor: string;
  level: PlantLevel;
  filters: string[];
  image: string;
  categoryKeys: string[];
  requirements: {
    light: "Low" | "Indirect" | "Full Sun";
    water: "Low" | "Moderate" | "High";
    humidity: string;
  };
  petSafe: boolean;
}

export const PLANTS: Plant[] = [
  {
    key: "monstera",
    name: "Monstera Deliciosa",
    scientificName: "Monstera deliciosa",
    desc: "Iconic Swiss-cheese leaves. Highly effective at filtering formaldehyde while adding a bold tropical feel.",
    badge: "AQI High",
    badgeIcon: "air-filter",
    badgeIconColor: "#006093",
    level: "Moderate",
    filters: ["Formaldehyde", "Xylene"],
    image:
      "https://plus.unsplash.com/premium_photo-1663962158789-0ab624c4f17d?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8bW9uc3RlcmF8ZW58MHx8MHx8fDA%3D",
    categoryKeys: ["all", "air"],
    requirements: { light: "Indirect", water: "Moderate", humidity: "60%+" },
    petSafe: false,
  },
  {
    key: "peacelily",
    name: "Peace Lily",
    scientificName: "Spathiphyllum",
    desc: "A powerhouse air cleaner that tackles ammonia and benzene. It literally 'droops' to tell you it's thirsty.",
    badge: "Pure Air",
    badgeIcon: "leaf",
    badgeIconColor: "#16a34a",
    level: "Moderate",
    filters: ["Ammonia", "Benzene", "Trichloroethylene"],
    image:
      "https://images.unsplash.com/photo-1593691509543-c55fb32d8de5?w=800&q=80",
    categoryKeys: ["all", "air", "lowlight"],
    requirements: { light: "Low", water: "High", humidity: "50%+" },
    petSafe: false,
  },
  {
    key: "aloe",
    name: "Aloe Vera",
    scientificName: "Aloe barbadensis miller",
    desc: "The 'Bio-indicator'—Aloe develops brown spots when air chemicals are high, alerting you to poor AQI.",
    badge: "Healing",
    badgeIcon: "medical-bag",
    badgeIconColor: "#ef4444",
    level: "Beginner",
    filters: ["Chemicals", "Formaldehyde"],
    image:
      "https://images.unsplash.com/photo-1587334274328-64186a80aeee?w=800&q=80",
    categoryKeys: ["all", "succulent"],
    requirements: { light: "Full Sun", water: "Low", humidity: "30%+" },
    petSafe: false,
  },
  {
    key: "pothos",
    name: "Golden Pothos",
    scientificName: "Epipremnum aureum",
    desc: "Commonly called 'Devil's Ivy' because it's nearly impossible to kill. Perfect for filtering indoor toxins.",
    badge: "Easy Care",
    badgeIcon: "sprout",
    badgeIconColor: "#16a34a",
    level: "Beginner",
    filters: ["Benzene", "Xylene", "Toluene"],
    image:
      "https://images.unsplash.com/photo-1558693168-c370615b54e0?w=800&q=80",
    categoryKeys: ["all", "air", "lowlight"],
    requirements: { light: "Low", water: "Low", humidity: "40%+" },
    petSafe: false,
  },
  {
    key: "snakeplant",
    name: "Snake Plant",
    scientificName: "Dracaena trifasciata",
    desc: "Unique for converting CO2 into Oxygen at night, making it the ideal plant for bedroom air quality.",
    badge: "Oxygen+",
    badgeIcon: "weather-windy",
    badgeIconColor: "#2563eb",
    level: "Beginner",
    filters: ["Nitrogen Oxide", "Formaldehyde"],
    image:
      "https://images.unsplash.com/photo-1572688484438-313a6e50c333?w=800&q=80",
    categoryKeys: ["all", "air", "lowlight", "succulent"],
    requirements: { light: "Low", water: "Low", humidity: "30%+" },
    petSafe: false,
  },
  {
    key: "spider",
    name: "Spider Plant",
    scientificName: "Chlorophytum comosum",
    desc: "A champion at removing carbon monoxide. Produces 'spiderettes' that are easy to propagate.",
    badge: "Pet Safe",
    badgeIcon: "paw",
    badgeIconColor: "#8b5cf6",
    level: "Beginner",
    filters: ["Carbon Monoxide", "Formaldehyde"],
    image:
      "https://images.unsplash.com/photo-1668117653442-dd03862e957f?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8U3BpZGVyJTIwUGxhbnR8ZW58MHx8MHx8fDA%3D",
    categoryKeys: ["all", "air", "pet"],
    requirements: { light: "Indirect", water: "Moderate", humidity: "40%+" },
    petSafe: true,
  },
  {
    key: "fern",
    name: "Boston Fern",
    scientificName: "Nephrolepis exaltata",
    desc: "Acts as a natural humidifier. It removes more formaldehyde than almost any other plant found in homes.",
    badge: "Humidity",
    badgeIcon: "water",
    badgeIconColor: "#0ea5e9",
    level: "Moderate",
    filters: ["Formaldehyde", "Xylene"],
    image:
      "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?w=800&q=80",
    categoryKeys: ["all", "air", "pet"],
    requirements: { light: "Indirect", water: "High", humidity: "70%+" },
    petSafe: true,
  },
  {
    key: "zz_plant",
    name: "ZZ Plant",
    scientificName: "Zamioculcas zamiifolia",
    desc: "The ultimate low-light survivor. It filters volatile organic compounds silently in any corner.",
    badge: "Resilient",
    badgeIcon: "arm-flex",
    badgeIconColor: "#4b5563",
    level: "Beginner",
    filters: ["Xylene", "Toluene", "Benzene"],
    image:
      "https://images.unsplash.com/photo-1632207691143-643e2a9a9361?w=800&q=80",
    categoryKeys: ["all", "air", "lowlight"],
    requirements: { light: "Low", water: "Low", humidity: "30%+" },
    petSafe: false,
  },
  {
    key: "rubber_plant",
    name: "Rubber Plant",
    scientificName: "Ficus elastica",
    desc: "Stunning glossy leaves that absorb carbon monoxide and cleaning chemical residue.",
    badge: "Hardy",
    badgeIcon: "shield-check",
    badgeIconColor: "#059669",
    level: "Beginner",
    filters: ["Carbon Monoxide", "Formaldehyde"],
    image:
      "https://images.unsplash.com/photo-1545241047-6083a3684587?w=800&q=80",
    categoryKeys: ["all", "air"],
    requirements: { light: "Indirect", water: "Moderate", humidity: "40%+" },
    petSafe: false,
  },
  {
    key: "fiddle_leaf",
    name: "Fiddle Leaf Fig",
    scientificName: "Ficus lyrata",
    desc: "Large leaf surface area makes it a powerhouse for trapping dust and broad-spectrum toxins.",
    badge: "Statement",
    badgeIcon: "star-face",
    badgeIconColor: "#f59e0b",
    level: "Advanced",
    filters: ["Formaldehyde", "Benzene"],
    image:
      "https://images.unsplash.com/photo-1598880940080-ff9a29891b85?w=800&q=80",
    categoryKeys: ["all", "air"],
    requirements: { light: "Indirect", water: "Moderate", humidity: "50%+" },
    petSafe: false,
  },
  {
    key: "calathea_orb",
    name: "Calathea Orbifolia",
    scientificName: "Goeppertia orbifolia",
    desc: "Silver-striped leaves that pray at night. Acts as a natural high-efficiency humidifier.",
    badge: "Humidity+",
    badgeIcon: "water-percent",
    badgeIconColor: "#0ea5e9",
    level: "Moderate",
    filters: ["Formaldehyde", "Xylene"],
    image:
      "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=800&q=80",
    categoryKeys: ["all", "air", "pet"],
    requirements: { light: "Indirect", water: "High", humidity: "60%+" },
    petSafe: true,
  },
  {
    key: "english_ivy",
    name: "English Ivy",
    scientificName: "Hedera helix",
    desc: "A climbing vine that excels at reducing airborne mold spores—ideal for bathrooms.",
    badge: "Mold Filter",
    badgeIcon: "bacteria-outline",
    badgeIconColor: "#7c2d12",
    level: "Moderate",
    filters: ["Mold Spores", "Benzene"],
    image:
      "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80",
    categoryKeys: ["all", "air"],
    requirements: { light: "Indirect", water: "Moderate", humidity: "50%+" },
    petSafe: false,
  },
  {
    key: "areca_palm",
    name: "Areca Palm",
    scientificName: "Dypsis lutescens",
    desc: "One of the best overall air purifiers. It releases massive amounts of moisture into the air.",
    badge: "Natural AC",
    badgeIcon: "fan",
    badgeIconColor: "#10b981",
    level: "Moderate",
    filters: ["Xylene", "Toluene"],
    image:
      "https://images.unsplash.com/photo-1709215992319-e10ecbbe3c98?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8YXJlY2ElMjBwYWxtfGVufDB8fDB8fHww",
    categoryKeys: ["all", "air", "pet"],
    requirements: { light: "Full Sun", water: "High", humidity: "60%+" },
    petSafe: true,
  },
  {
    key: "money_tree",
    name: "Money Tree",
    scientificName: "Pachira aquatica",
    desc: "Famous for its braided trunk. Very effective at cleaning synthetic chemicals from new furniture.",
    badge: "Prosperity",
    badgeIcon: "currency-usd",
    badgeIconColor: "#16a34a",
    level: "Beginner",
    filters: ["Formaldehyde", "Benzene"],
    image:
      "https://images.unsplash.com/photo-1663436145336-1c5bb2c373c1?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fG1vbmV5JTIwdHJlZXxlbnwwfHwwfHx8MA%3D%3D",
    categoryKeys: ["all", "air", "pet"],
    requirements: { light: "Indirect", water: "Moderate", humidity: "50%+" },
    petSafe: true,
  },
  {
    key: "bird_of_paradise",
    name: "Bird of Paradise",
    scientificName: "Strelitzia reginae",
    desc: "Massive banana-like leaves that process heavy amounts of CO2 during the day.",
    badge: "Oxygen Max",
    badgeIcon: "weather-sunny",
    badgeIconColor: "#fb923c",
    level: "Moderate",
    filters: ["CO2", "Dust"],
    image:
      "https://images.unsplash.com/photo-1598512752271-33f913a5af13?w=800&q=80",
    categoryKeys: ["all"],
    requirements: { light: "Full Sun", water: "Moderate", humidity: "50%+" },
    petSafe: false,
  },
  {
    key: "jade_plant",
    name: "Jade Plant",
    scientificName: "Crassula ovata",
    desc: "A long-lived succulent that requires very little water. Good at capturing particulates.",
    badge: "Longevity",
    badgeIcon: "infinity",
    badgeIconColor: "#064e3b",
    level: "Beginner",
    filters: ["Particulates", "Toluene"],
    image:
      "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=800&q=80",
    categoryKeys: ["all", "succulent"],
    requirements: { light: "Full Sun", water: "Low", humidity: "30%+" },
    petSafe: false,
  },
  {
    key: "parlor_palm",
    name: "Parlor Palm",
    scientificName: "Chamaedorea elegans",
    desc: "A compact palm that thrives in low light and is entirely safe for your pets.",
    badge: "Safe Space",
    badgeIcon: "home-heart",
    badgeIconColor: "#db2777",
    level: "Beginner",
    filters: ["Benzene", "Trichloroethylene"],
    image:
      "https://plus.unsplash.com/premium_photo-1663961915616-0ebe4f6f73db?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cGFybG9yJTIwcGFsbXxlbnwwfHwwfHx8MA%3D%3D",
    categoryKeys: ["all", "lowlight", "pet"],
    requirements: { light: "Low", water: "Moderate", humidity: "50%+" },
    petSafe: true,
  },
  {
    key: "dracaena",
    name: "Dracaena Marginata",
    scientificName: "Dracaena marginata",
    desc: "Red-edged architectural leaves that are highly efficient at removing xylene.",
    badge: "Modern",
    badgeIcon: "format-paint",
    badgeIconColor: "#991b1b",
    level: "Beginner",
    filters: ["Xylene", "Trichloroethylene"],
    image:
      "https://images.unsplash.com/photo-1493962853295-0fd70327578a?w=800&q=80",
    categoryKeys: ["all", "air", "lowlight"],
    requirements: { light: "Low", water: "Low", humidity: "40%+" },
    petSafe: false,
  },
  {
    key: "cast_iron",
    name: "Cast Iron Plant",
    scientificName: "Aspidistra elatior",
    desc: "True to its name, it survives low light and dust where other plants fail.",
    badge: "Indestructible",
    badgeIcon: "weight-lifter",
    badgeIconColor: "#1e293b",
    level: "Beginner",
    filters: ["Chemicals", "Smoke"],
    image:
      "https://images.unsplash.com/photo-1602923668104-8f9e03e77e62?w=800&q=80",
    categoryKeys: ["all", "lowlight"],
    requirements: { light: "Low", water: "Low", humidity: "30%+" },
    petSafe: true,
  },
  {
    key: "chinese_evergreen",
    name: "Chinese Evergreen",
    scientificName: "Aglaonema",
    desc: "Tolerates low light and dry air while filtering out a broad range of toxins.",
    badge: "Office Hero",
    badgeIcon: "briefcase-outline",
    badgeIconColor: "#1e40af",
    level: "Beginner",
    filters: ["Benzene", "Formaldehyde"],
    image:
      "https://images.unsplash.com/photo-1568151492546-1db658d0fc42?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8Y2hpbmVzZSUyMGV2ZXJncmVlbnxlbnwwfHwwfHx8MA%3D%3D",
    categoryKeys: ["all", "lowlight"],
    requirements: { light: "Low", water: "Low", humidity: "40%+" },
    petSafe: false,
  },
  {
    key: "prayer_plant",
    name: "Prayer Plant",
    scientificName: "Maranta leuconeura",
    desc: "Stunning variegated leaves that fold up at night. Great for humidity sensing.",
    badge: "Zen",
    badgeIcon: "meditation",
    badgeIconColor: "#6d28d9",
    level: "Moderate",
    filters: ["Formaldehyde"],
    image:
      "https://plus.unsplash.com/premium_photo-1673615874537-65fdf1c772ee?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8UHJheWVyJTIwUGxhbnR8ZW58MHx8MHx8fDA%3D",
    categoryKeys: ["all", "pet"],
    requirements: { light: "Indirect", water: "High", humidity: "60%+" },
    petSafe: true,
  },
];

export const CATEGORIES = [
  { key: "all", label: "All Plants", icon: "database" },
  { key: "air", label: "Air Purifiers", icon: "air-filter" },
  { key: "lowlight", label: "Low Light", icon: "weather-night" },
  { key: "pet", label: "Pet Friendly", icon: "paw" },
  { key: "succulent", label: "Succulents", icon: "cactus" },
];
